"""What every generator here shares: the environment pinned, the configurations, and
LaTeX/CSV writers that land in `paper_tests/out/`.

Nothing in the paper is typed by hand from a terminal: each script writes a `.csv`
(the numbers, for a reader with a script) and a `.tex` fragment (a `tabular`, for
`\\input`), both named after the script, plus a `.json` where the raw rows are worth
keeping. Every fragment starts with a comment line saying which script, which tree
and which machine produced it, in the same spirit as the reference matrices'
headers.
"""

from __future__ import annotations

import csv
import json
import os
import sys
import time
from pathlib import Path

import jax

jax.config.update("jax_enable_x64", True)
os.environ.setdefault("JAX_PLATFORMS", "cpu")

ROOT = Path(__file__).resolve().parent.parent
OUT = Path(__file__).resolve().parent / "out"
OUT.mkdir(exist_ok=True)

sys.path.insert(0, str(ROOT))

from functional_process.cottax import native  # noqa: E402
from functional_process.cottax.run_cold_matrix import (  # noqa: E402
    _git,
    cottax_tree,
    machine,
)

CONFIGURATIONS = tuple(native.CONFIGURATIONS)
"""The seven reference input files, in the order every table lists them."""

STELLARATORS = tuple(c for c in CONFIGURATIONS if "helias" in c)

RECIPES = ("hand", "jacobi", "gauss_seidel", "gauss_seidel_minimal")
"""The cuts a table compares: `mda.CUTS` and the three `recipes.RECIPES`."""

LABEL = {
    "hand": "hand",
    "jacobi": "Jacobi",
    "gauss_seidel": "GS (call order)",
    "gauss_seidel_minimal": "GS (minimal)",
}


def stem(path: str) -> str:
    return Path(path).name.replace(".IN.DAT", "")


def tex_name(name: str) -> str:
    """A configuration name as LaTeX: underscores escaped."""
    return name.replace("_", r"\_")


def cut_for(name: str):
    """`None` for the hand-measured cuts, else the recipe."""
    from functional_process.cottax.recipes import recipe  # noqa: PLC0415

    return None if name == "hand" else recipe(name)


def provenance(script: str) -> str:
    """One comment line: script, tree, cottax, machine, time."""
    head = _git("rev-parse", "--short", "HEAD", cwd=ROOT) or "unknown"
    dirty = " (+uncommitted)" if _git("status", "--porcelain", cwd=ROOT) else ""
    return (
        f"% generated by paper_tests/{script} on {time.strftime('%Y-%m-%d %H:%M')}; "
        f"PROCESS {head}{dirty}; cottax {cottax_tree().split(' at ')[0]}; {machine()}"
    )


def write_csv(script: str, rows: list[dict], name: str | None = None) -> Path:
    path = OUT / f"{name or script.removesuffix('.py')}.csv"
    if not rows:
        path.write_text("")
        return path
    keys = list(dict.fromkeys(k for row in rows for k in row))
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=keys)
        writer.writeheader()
        for row in rows:
            writer.writerow({k: _cell(row.get(k)) for k in keys})
    return path


def write_json(script: str, payload, name: str | None = None) -> Path:
    path = OUT / f"{name or script.removesuffix('.py')}.json"
    path.write_text(json.dumps(payload, indent=1, default=str))
    return path


def write_tex(script: str, header: list[str], rows: list[list], name: str | None = None,
              align: str | None = None, caption_note: str = "") -> Path:
    """A booktabs `tabular` fragment. `header` and each row are already LaTeX."""
    path = OUT / f"{name or script.removesuffix('.py')}.tex"
    align = align or ("l" + "r" * (len(header) - 1))
    lines = [provenance(script)]
    if caption_note:
        lines.append(f"% {caption_note}")
    lines += [
        f"\\begin{{tabular}}{{{align}}}",
        "\\toprule",
        " & ".join(header) + r" \\",
        "\\midrule",
        *(" & ".join(str(c) for c in row) + r" \\" for row in rows),
        "\\bottomrule",
        "\\end{tabular}",
        "",
    ]
    path.write_text("\n".join(lines))
    return path


def _cell(value):
    if value is None:
        return ""
    if isinstance(value, float):
        return f"{value:.10g}"
    return value


def fmt(value, digits=3) -> str:
    """A number for a table cell, or `--`."""
    if value is None:
        return "--"
    if isinstance(value, str):
        return value
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, int):
        return str(value)
    return f"{value:.{digits}f}"


def sci(value) -> str:
    if value is None:
        return "--"
    return f"{value:.2e}"
