"""**Per-node validation**: run each generated `@wp.func` against `defn.fn` in JAX, at
the same inputs, swept over several draws.

This is the check the jaxpr backend is worth having. The previous design could only ever
compare one whole sub-DAG at one input point, so a single number certified forty
functions at once and any node whose contribution happened to cancel, or to be swamped
by a larger term, was certified for free. Here every node is its own experiment: a
disagreement is attributed to the node that caused it, and a node that is never reached
by the assembled kernel is still checked.

**Swept, not sampled.** A previous agent found a real 1-ulp disagreement at 1 of 400
swept points that a single point missed entirely. Each node is evaluated at its ground
truth point plus `N_DRAWS - 1` multiplicative random perturbations of it (log-uniform,
so a positive physical quantity stays positive and stays within its own order of
magnitude -- an additive draw around, say, a 1e20 density produces nothing but noise).

Integer-typed reads are held FIXED across the sweep. An integer read in this graph is an
index or a species selector; perturbing one does not test the emitted arithmetic, it
tests whether an out-of-range index happens to be caught, and that is a different
question.

Run:

    python -m functional_process.cottax.warp.jaxpr_validate helias_5b
"""
from __future__ import annotations

import importlib.util
import os
import re
import sys

import jax

jax.config.update("jax_enable_x64", True)

import jax.numpy as jnp
import numpy as np

from .jaxpr_backend import jaxpr_leaves, node_values

N_DRAWS = 8
"""Ground truth plus 7 perturbations. Enough that a branch-dependent or
argument-order bug shows up; small enough that 150 nodes stay a seconds-scale run."""

SPREAD = 0.35
"""Log-uniform half-width of the multiplicative perturbation, i.e. each float read is
multiplied by `exp(U(-0.35, 0.35))` -- roughly x0.70 to x1.42."""

AGREEMENT_RTOL = 1e-12
"""Same gate as `harness.AGREEMENT_RTOL`, and for the same reason: it is a bug
detector, not an accuracy claim. The worst relative difference is reported as a number
regardless."""

GEN_DIR = "functional_process/warp"


def draws(base, rng, n=N_DRAWS, spread=SPREAD):
    """`n` input tuples for one node: `base` itself first, then multiplicative
    perturbations of every FLOAT read (integer/bool reads held fixed, see the module
    docstring)."""
    out = [list(base)]
    for _ in range(n - 1):
        row = []
        for v in base:
            a = np.asarray(v)
            if np.issubdtype(a.dtype, np.floating):
                f = np.exp(rng.uniform(-spread, spread, size=a.shape))
                row.append(jnp.asarray(a * f))
            else:
                row.append(jnp.asarray(a))
        out.append(row)
    return out


def _validation_kernel(entry, index: int) -> str:
    """One `@wp.kernel` wrapping one node's `@wp.func`, reading its arguments from a
    row of `inp` and writing its returns to a row of `out`."""
    n_in, n_out = len(entry.inputs), len(entry.outputs)
    args = ", ".join(f"inp[tid, {i}]" for i in range(n_in))
    lines = ["@wp.kernel",
             f"def check_{index}(inp: wp.array2d(dtype=wp.float64), "
             f"out: wp.array2d(dtype=wp.float64)):",
             "    tid = wp.tid()"]
    if n_out == 1:
        lines.append(f"    r0 = {entry.fn}({args})")
    else:
        rets = ", ".join(f"r{i}" for i in range(n_out))
        lines.append(f"    {rets} = {entry.fn}({args})")
    for i in range(n_out):
        lines.append(f"    out[tid, {i}] = r{i}")
    return "\n".join(lines) + "\n"


def _failing_func(err_text: str) -> str | None:
    names = re.findall(r'Error while parsing function "([^"]+)"', err_text)
    return names[-1] if names else None


def build_module(entries, config: str, tag: str):
    """Write and import ONE module holding every node's `@wp.func` plus one validation
    kernel each. One module means one Warp compile for the whole config; a codegen
    failure names the function it came from and the caller drops that node and retries
    (`validate`, below), so a single bad node cannot hide the rest."""
    src = ['"""GENERATED by functional_process/cottax/warp/jaxpr_backend -- do not '
           'hand-edit."""',
           "import warp as wp", ""]
    for e in entries:
        src.append(e.source)
    for i, e in enumerate(entries):
        src.append(_validation_kernel(e, i))
    text = "\n".join(src)
    os.makedirs(GEN_DIR, exist_ok=True)
    path = f"{GEN_DIR}/_jaxpr_nodes_{config}.py"
    with open(path, "w") as f:
        f.write(text)
    spec = importlib.util.spec_from_file_location(f"_jaxpr_nodes_{config}_{tag}", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod, path


def validate(config: str, verbose: bool = True):
    """`(entries, results, refused)` -- the emitted entries that COMPILE, one result
    row per node, and everything refused (by the backend or by Warp codegen).

    A result row is
    `{node, n_draws, n_compared, worst_rel, verdict, ...}`; `verdict` is `PASS`,
    `FAIL`, or `NO-FINITE` when both engines produced NaN/inf at every draw (a domain
    issue with the perturbed input, not a disagreement -- reported, never silently
    counted as a pass).
    """
    import warp as wp

    wp.init()

    from functional_process.cottax import native as _native
    from .assemble import _assemble

    drive, _ = _assemble(config)
    cold = _native.native_reference(
        f"tests/regression/input_files/{config}.IN.DAT").cold
    entries, refused, _ = jaxpr_leaves(config, drive=drive, cold=cold)
    if verbose:
        print(f"[jaxpr] {config}: {len(entries)} emitted, {len(refused)} refused "
              f"out of {len(entries) + len(refused)} nodes")

    sub = drive.body.subgraph
    by_node = {n.path_str(): sub[n] for n in sub.topological_order}

    # Scalar-only for now: a node with an array-valued read has no float64-column
    # binding in the validation kernel, so it cannot be checked this way. It is
    # reported here rather than dropped silently.
    checkable, unbindable = [], []
    base_vals = {}
    for e in entries:
        vals = node_values(cold, by_node[e.node])
        if any(np.asarray(v).size != 1 for v in vals):
            unbindable.append((e.node, "array-valued read -- no scalar column binding"))
            continue
        base_vals[e.node] = [np.asarray(v).reshape(()) for v in vals]
        checkable.append(e)

    # Compile, dropping any node Warp's own codegen rejects, and retry -- the same
    # "measured, not assumed" loop `harness.py` uses.
    mod = None
    for attempt in range(30):
        if not checkable:
            break
        try:
            mod, path = build_module(checkable, config, f"a{attempt}")
            break
        except Exception as exc:
            bad = _failing_func(str(exc))
            hit = [e for e in checkable if e.fn == bad]
            if not hit:
                if verbose:
                    print(f"[jaxpr] codegen failure not attributable to one function: "
                          f"{str(exc)[-400:]}")
                return checkable, [], refused + unbindable
            for e in hit:
                refused.append((e.node, f"Warp codegen: {str(exc)[:160]}"))
            checkable = [e for e in checkable if e.fn != bad]
    if mod is None:
        return [], [], refused + unbindable

    rng = np.random.default_rng(20260906)
    results = []
    for i, e in enumerate(checkable):
        defn = by_node[e.node]
        rows = draws(base_vals[e.node], rng)
        n_in, n_out = len(e.inputs), len(e.outputs)

        jax_out = np.full((len(rows), n_out), np.nan)
        ok_jax = True
        for r, row in enumerate(rows):
            try:
                res = defn.fn(*row)
            except Exception:
                ok_jax = False
                break
            flat = jax.tree_util.tree_leaves(res)
            if len(flat) != n_out:
                ok_jax = False
                break
            jax_out[r] = [float(np.asarray(x).reshape(())) for x in flat]
        if not ok_jax:
            results.append({"node": e.node, "verdict": "JAX-ERROR", "worst_rel": np.nan,
                            "n_compared": 0, "n_out": n_out})
            continue

        inp = wp.array(np.array([[float(v) for v in row] for row in rows]),
                       dtype=wp.float64, device="cpu")
        out = wp.zeros((len(rows), n_out), dtype=wp.float64, device="cpu")
        kern = getattr(mod, f"check_{i}")
        try:
            wp.launch(kern, dim=len(rows), inputs=[inp, out], device="cpu")
            wp.synchronize()
        except Exception as exc:
            results.append({"node": e.node, "verdict": "WARP-ERROR",
                            "worst_rel": np.nan, "n_compared": 0, "n_out": n_out,
                            "detail": str(exc)[:200]})
            continue
        wout = out.numpy()

        rel = np.abs(wout - jax_out) / np.maximum(np.abs(jax_out), 1e-300)
        # Both engines NaN/inf at a draw is a property of the perturbed input, not a
        # disagreement; both engines producing the SAME non-finite value counts as
        # agreement, and only one of them doing so is a real failure.
        both_nan = ~np.isfinite(wout) & ~np.isfinite(jax_out)
        same_sign_inf = np.isinf(wout) & np.isinf(jax_out) & (np.sign(wout) == np.sign(jax_out))
        agree_nonfinite = both_nan | same_sign_inf
        one_sided = (~np.isfinite(wout) ^ ~np.isfinite(jax_out))
        comparable = np.isfinite(rel) & ~agree_nonfinite
        worst = float(rel[comparable].max()) if comparable.any() else np.nan
        if one_sided.any():
            verdict = "FAIL"
        elif not comparable.any():
            verdict = "NO-FINITE"
        else:
            verdict = "PASS" if worst <= AGREEMENT_RTOL else "FAIL"
        results.append({"node": e.node, "fn": e.fn, "verdict": verdict,
                        "worst_rel": worst, "n_compared": int(comparable.sum()),
                        "n_draws": len(rows), "n_out": n_out, "n_in": n_in,
                        "n_eqns": e.n_eqns,
                        "one_sided": int(one_sided.sum())})

    if verbose:
        _report(config, results, refused, unbindable)
    return checkable, results, refused + unbindable


def _report(config, results, refused, unbindable):
    from collections import Counter

    counts = Counter(r["verdict"] for r in results)
    print(f"\n[jaxpr] === per-node validation, {config} "
          f"({N_DRAWS} draws/node) ===")
    for v in ("PASS", "FAIL", "NO-FINITE", "JAX-ERROR", "WARP-ERROR"):
        if counts.get(v):
            print(f"    {v:<11} {counts[v]}")
    fails = [r for r in results if r["verdict"] == "FAIL"]
    if fails:
        print("\n[jaxpr] failing nodes:")
        for r in sorted(fails, key=lambda r: -(r["worst_rel"] if np.isfinite(r["worst_rel"]) else 0)):
            print(f"    {r['node']:<62} worst_rel={r['worst_rel']:.3e} "
                  f"one-sided={r.get('one_sided', 0)}")
    # A non-PASS that is not a FAIL is still not a pass: name it, so "144 PASS" is
    # never read as "145 nodes checked".
    for v in ("NO-FINITE", "JAX-ERROR", "WARP-ERROR"):
        rows = [r for r in results if r["verdict"] == v]
        if rows:
            print(f"\n[jaxpr] {v} (checked, but no comparable value at any draw):")
            for r in rows:
                print(f"    {r['node']}")
    passing = [r for r in results
               if r["verdict"] == "PASS" and np.isfinite(r["worst_rel"])]
    if passing:
        worst_row = max(passing, key=lambda r: r["worst_rel"])
        print(f"\n[jaxpr] worst relative difference among PASSING nodes: "
              f"{worst_row['worst_rel']:.3e}  (gate {AGREEMENT_RTOL:.0e})  at "
              f"{worst_row['node']}")
        inexact = sorted((r for r in passing if r["worst_rel"] > 0),
                         key=lambda r: -r["worst_rel"])
        if inexact:
            print(f"[jaxpr] {len(inexact)} passing node(s) not bit-exact:")
            for r in inexact:
                print(f"    {r['node']:<62} {r['worst_rel']:.3e}")
        passing = [r["worst_rel"] for r in passing]
        nonzero = [p for p in passing if p > 0]
        print(f"[jaxpr] {len(passing) - len(nonzero)}/{len(passing)} passing nodes are "
              f"BIT-EXACT across every draw")
    print(f"\n[jaxpr] refused ({len(refused) + len(unbindable)}):")
    for n, why in list(refused) + list(unbindable):
        print(f"    {n:<62} {why[:100]}")


if __name__ == "__main__":
    cfg = sys.argv[1] if len(sys.argv) > 1 else "helias_5b"
    validate(cfg)
