"""One line per ported unit: what is compared to what, and how far apart it came out.

**The artefact a human signs off on.** The harness is 668 contracts and ~21,500 lines,
41 % of which is sample numbers and 6 % of which -- about two lines per unit -- is the
part a reviewer has to check: *this* PROCESS function against *this* ported one. Nobody
reads 21,500 lines to approve a port, so the two lines are extracted here instead, for
every unit at once, with the measured agreement beside them.

It is **generated by running the comparison**, not by reading the source, so it cannot
drift from what the suite actually does: a unit whose reference was quietly repointed
shows a different name here on the next run.

    $PY -m functional_process.cottax._harness.signoff [--out FILE]

Columns: the PROCESS callable the unit is checked against, the ported callable, the tier,
how many sample points and where they came from, and the worst relative difference over
all of them. `dom` counts points PROCESS itself rejects, where the contract asks the port
for a non-finite value rather than for agreement.

**Where a row names a `_reference_*` rather than a PROCESS function**, the unit's
reference is a hand-written adapter and the adapter *is* the definition of what is being
compared -- 199 of 677 rows name the PROCESS callable directly, the rest name the adapter
that drives it. A reviewer who wants the underlying method reads that one adapter; the
alternative would be to unwrap a closure and guess, which would be a worse answer than an
honest name. Rows are sorted worst-agreement first, so the ones worth a second look are
at the top and the machine-precision majority is below them.
"""

import argparse
import pathlib
import sys

import numpy as np

from functional_process.cottax._harness.contracts import Tier1Contract, Tier2Contract


def _name(fn) -> str:
    """A callable's importable name, as a reviewer would look it up."""
    fn = getattr(fn, "__func__", fn)
    fn = getattr(fn, "func", fn)  # functools.partial
    module = getattr(fn, "__module__", "?") or "?"
    return f"{module.split('.')[-1]}.{getattr(fn, '__qualname__', repr(fn))}"


def _contracts():
    """Every declared contract, by importing the case tree and walking subclasses."""
    import importlib  # noqa: PLC0415 -- importing the case tree is what this does
    import pkgutil  # noqa: PLC0415

    import functional_process.tests as cases  # noqa: PLC0415

    def load(name):
        """One module, reported rather than raised: a bad one must not lose the rest."""
        try:
            importlib.import_module(name)
        except Exception as failure:  # noqa: BLE001 -- reported, never fatal
            print(f"# could not import {name}: {failure}", file=sys.stderr)

    for module in pkgutil.walk_packages(cases.__path__, cases.__name__ + "."):
        load(module.name)

    def descendants(cls):
        for sub in cls.__subclasses__():
            yield sub
            yield from descendants(sub)

    seen = {c for base in (Tier1Contract, Tier2Contract) for c in descendants(base)}
    return sorted(seen, key=lambda c: (c.__module__, c.__qualname__))


def _worst(contract) -> tuple[float, int, int, str]:
    """`(worst relative difference, points compared, domain rejections, note)`."""
    case = contract()
    worst, compared, domain = 0.0, 0, 0
    for sample in contract.samples:
        try:
            expected, domain_error = case._reference_or_domain_error(
                dict(sample.kwargs)
            )
        except Exception as failure:  # noqa: BLE001 -- a note, not an exit
            return float("nan"), compared, domain, f"reference failed: {failure}"
        if domain_error is not None:
            domain += 1
            continue
        try:
            actual = np.asarray(case.ported(**sample.kwargs), dtype=float).reshape(-1)
        except Exception as failure:  # noqa: BLE001
            return float("nan"), compared, domain, f"port failed: {failure}"
        want = np.asarray(expected, dtype=float).reshape(-1)
        if actual.shape != want.shape:
            return float("nan"), compared, domain, "shape mismatch"
        scale = np.where(np.abs(want) > 0, np.abs(want), 1.0)
        worst = max(worst, float(np.max(np.abs(actual - want) / scale)))
        compared += 1
    return worst, compared, domain, ""


def rows():
    """One record per contract."""
    out = []
    for contract in _contracts():
        provenance = sorted({s.provenance for s in contract.samples})
        worst, compared, domain, note = _worst(contract)
        out.append({
            "unit": getattr(contract, "audit_record", "?"),
            "case": f"{contract.__module__.split('.')[-1]}.{contract.__qualname__}",
            "reference": _name(contract.reference),
            "ported": _name(contract.ported),
            "tier": 1 if issubclass(contract, Tier1Contract) else 2,
            "samples": len(contract.samples),
            "provenance": ",".join(provenance),
            "compared": compared,
            "domain": domain,
            "worst_rel": worst,
            "note": note,
        })
    return out


def render(records) -> str:
    """The table, widest columns first so the eye lands on the comparison."""
    header = (
        "# Generated by `$PY -m functional_process.cottax._harness.signoff`;"
        " do not hand-edit.\n#\n"
        "# One row per ported unit. `worst rel` is the largest relative difference"
        " between\n"
        "# the port and PROCESS over that unit's sample points; `dom` counts points"
        " PROCESS\n"
        "# itself rejects, where the contract asks the port for a non-finite value"
        " instead\n# of agreement.\n"
    )
    columns = (
        f"{'PROCESS reference':<52} {'ported':<52} {'T':>1}"
        f" {'n':>4} {'dom':>4} {'worst rel':>11}  provenance"
    )
    lines = [header, columns]
    for r in sorted(records, key=lambda r: -(r["worst_rel"] or 0)):
        worst = "nan" if r["worst_rel"] != r["worst_rel"] else f"{r['worst_rel']:.3e}"
        lines.append(
            f"{r['reference']:<52} {r['ported']:<52} {r['tier']:>1} "
            f"{r['samples']:>4} {r['domain']:>4} {worst:>11}  {r['provenance']}"
            + (f"   {r['note']}" if r["note"] else "")
        )
    finite = [r["worst_rel"] for r in records if r["worst_rel"] == r["worst_rel"]]
    total = (
        f"{len(records)} units; {sum(r['samples'] for r in records)} sample points;"
        f" {sum(r['domain'] for r in records)} domain rejections."
    )
    lines += ["", total]
    if finite:
        lines.append(f"worst relative difference anywhere: {max(finite):.3e}")
    return "\n".join(lines) + "\n"


def main(argv=None):
    """Write the table to `--out`, or to stdout."""
    parser = argparse.ArgumentParser(prog="signoff")
    parser.add_argument("--out", default=None)
    args = parser.parse_args(argv)
    text = render(rows())
    if args.out:
        pathlib.Path(args.out).write_text(text)
        print(f"wrote {args.out}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
